[package]
name = "linked_lists"
version = "0.1.0"
edition = "2021"

[dependencies]
[workspace]

members = [
 "middle_linked_list", 
 "remove_duplicates_from_sorted_list"

 , "reverse_linked_list_II"]
